name: development-workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: === INSTALL APP ===
        run: npm install
      - name: === TEST UNIT ===
        run: npm run test:ci:unit
      - name: === [HEROKU][DEVELOPMENT]DEPLOY===
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "develop-gruposbf-cc"
          heroku_email: "barreiradev@gmail.com"